In [1]:
import numpy as np

def print_confusion_matrix(conf_matrix, title):
    labels = ['Negative', 'Neutral', 'Positive']
    
    print(title)
    
    # Header
    print(' ' * 16, end=' ')
    for label in labels:
        print(f'{label:>10}', end=' ')
    print()  # Newline
    
    # Confusion matrix rows
    for i, row in enumerate(conf_matrix):
        print(f'{labels[i]:<16}', end=' ')
        for value in row:
            print(f'{value:>10}', end=' ')
        print()  # Newline at the end of the row
    
    print()  # Blank line for separation
    print('Confusion Matrix:')
    print(conf_matrix)

# Confusion matrices
conf_matrix_fasttext = np.array([[2508, 488, 218], [264, 1296, 624], [270, 1273, 13550]])
conf_matrix_word2vec = np.array([[3023, 107, 84], [107, 1867, 210], [65, 362, 14666]])
conf_matrix_doc2vec = np.array([[3035, 87, 92], [108, 1873, 203], [74, 154, 14865]])

# Titles
title_fasttext = 'Confusion Matrix for Fasttext'
title_word2vec = 'Confusion Matrix for Word2vec'
title_doc2vec = 'Confusion Matrix for Doc2vec'

# Print the confusion matrices
print_confusion_matrix(conf_matrix_fasttext, title_fasttext)
print()
print_confusion_matrix(conf_matrix_word2vec, title_word2vec)
print()
print_confusion_matrix(conf_matrix_doc2vec, title_doc2vec)


Confusion Matrix for Fasttext
                   Negative    Neutral   Positive 
Negative               2508        488        218 
Neutral                 264       1296        624 
Positive                270       1273      13550 

Confusion Matrix:
[[ 2508   488   218]
 [  264  1296   624]
 [  270  1273 13550]]

Confusion Matrix for Word2vec
                   Negative    Neutral   Positive 
Negative               3023        107         84 
Neutral                 107       1867        210 
Positive                 65        362      14666 

Confusion Matrix:
[[ 3023   107    84]
 [  107  1867   210]
 [   65   362 14666]]

Confusion Matrix for Doc2vec
                   Negative    Neutral   Positive 
Negative               3035         87         92 
Neutral                 108       1873        203 
Positive                 74        154      14865 

Confusion Matrix:
[[ 3035    87    92]
 [  108  1873   203]
 [   74   154 14865]]
