In [2]:
import numpy as np

def print_confusion_matrix(conf_matrix, title):
    labels = ['Negative', 'Neutral', 'Positive']
    
    print(title)
    
    # Header
    print(' ' * 16, end=' ')
    for label in labels:
        print(f'{label:>10}', end=' ')
    print()  # Newline
    
    # Confusion matrix rows
    for i, row in enumerate(conf_matrix):
        print(f'{labels[i]:<16}', end=' ')
        for value in row:
            print(f'{value:>10}', end=' ')
        print()  # Newline at the end of the row
    
    print()  # Blank line for separation
    print('Confusion Matrix:')
    print(conf_matrix)

# Confusion matrices
conf_matrix_fasttext = np.array([[2796, 286, 132], [319, 1453, 412], [380, 1683, 13030]])
conf_matrix_word2vec = np.array([[3000, 75, 139], [105, 1607, 472], [63, 167, 14863]])
conf_matrix_doc2vec = np.array([[3030, 69, 115], [123, 1821, 240], [102, 94, 14897]])

# Titles
title_fasttext = 'Confusion Matrix for Fasttext'
title_word2vec = 'Confusion Matrix for Word2vec'
title_doc2vec = 'Confusion Matrix for Doc2vec'

# Print the confusion matrices
print_confusion_matrix(conf_matrix_fasttext, title_fasttext)
print()
print_confusion_matrix(conf_matrix_word2vec, title_word2vec)
print()
print_confusion_matrix(conf_matrix_doc2vec, title_doc2vec)


Confusion Matrix for Fasttext
                   Negative    Neutral   Positive 
Negative               2796        286        132 
Neutral                 319       1453        412 
Positive                380       1683      13030 

Confusion Matrix:
[[ 2796   286   132]
 [  319  1453   412]
 [  380  1683 13030]]

Confusion Matrix for Word2vec
                   Negative    Neutral   Positive 
Negative               3000         75        139 
Neutral                 105       1607        472 
Positive                 63        167      14863 

Confusion Matrix:
[[ 3000    75   139]
 [  105  1607   472]
 [   63   167 14863]]

Confusion Matrix for Doc2vec
                   Negative    Neutral   Positive 
Negative               3030         69        115 
Neutral                 123       1821        240 
Positive                102         94      14897 

Confusion Matrix:
[[ 3030    69   115]
 [  123  1821   240]
 [  102    94 14897]]
