In [1]:
import numpy as np

def print_confusion_matrix(conf_matrix, title):
    labels = ['Negative', 'Neutral', 'Positive']
    
    print(title)
    
    # Header
    print(' ' * 16, end=' ')
    for label in labels:
        print(f'{label:>10}', end=' ')
    print()  # Newline
    
    # Confusion matrix rows
    for i, row in enumerate(conf_matrix):
        print(f'{labels[i]:<16}', end=' ')
        for value in row:
            print(f'{value:>10}', end=' ')
        print()  # Newline at the end of the row
    
    print()  # Blank line for separation
    print('Confusion Matrix:')
    print(conf_matrix)

# Confusion matrices
conf_matrix_fasttext = np.array([[2632, 381, 201], [362, 1245, 577], [337, 1541, 13215]])
conf_matrix_word2vec = np.array([[3014, 135, 65], [142, 1800, 242], [243, 662, 14188]])
conf_matrix_doc2vec = np.array([[3070, 60, 84], [99, 1850, 235], [100, 154, 14839]])

# Titles
title_fasttext = 'Confusion Matrix for Fasttext'
title_word2vec = 'Confusion Matrix for Word2vec'
title_doc2vec = 'Confusion Matrix for Doc2vec'

# Print the confusion matrices
print_confusion_matrix(conf_matrix_fasttext, title_fasttext)
print()
print_confusion_matrix(conf_matrix_word2vec, title_word2vec)
print()
print_confusion_matrix(conf_matrix_doc2vec, title_doc2vec)


Confusion Matrix for Fasttext
                   Negative    Neutral   Positive 
Negative               2632        381        201 
Neutral                 362       1245        577 
Positive                337       1541      13215 

Confusion Matrix:
[[ 2632   381   201]
 [  362  1245   577]
 [  337  1541 13215]]

Confusion Matrix for Word2vec
                   Negative    Neutral   Positive 
Negative               3014        135         65 
Neutral                 142       1800        242 
Positive                243        662      14188 

Confusion Matrix:
[[ 3014   135    65]
 [  142  1800   242]
 [  243   662 14188]]

Confusion Matrix for Doc2vec
                   Negative    Neutral   Positive 
Negative               3070         60         84 
Neutral                  99       1850        235 
Positive                100        154      14839 

Confusion Matrix:
[[ 3070    60    84]
 [   99  1850   235]
 [  100   154 14839]]
